version: "3.7"

services:
  redis-db:
    image: redis:alpine
    container_name: reminder-db
    restart: unless-stopped
    command:
      - 'sh'
      - '-euc'
      - |
        exec redis-server --requirepass ${REDIS_PASSWORD}
    volumes: 
      - ${DOCKER_REDIS_VOLUME}/:/data:rw
      # if that does not work use
      # ./data:/data:rw


  reminder-bot:
    # optionally pre-build the image
    # image: reminder-bot:2024.02.19
    environment:
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    # optionally: mount the zuliprc file. First create a volume "reminder-bot_data" and store the file there (or use ./path/to/file)
    # volumes: 
    #  - /var/lib/docker/volumes/reminder-bot_data/_data/zuliprc:/app/zuliprc:ro
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reminder-bot
    restart: unless-stopped
    depends_on: 
      - redis-db
volumes:
  data:
